config/routes.rb
Quotify::Application.routes.draw do
  resources :users

  resources :quotes, :only => [:show, :create, :destroy] do 
    get 'history', :on => :collection
    resources :quote_images, :only => [:show, :create]
    resources :comments, :only => [:create, :new]
  end

  namespace :admin do
    resources :quotes, :only => [:new, :index, :edit, :update] do 
      resources :quote_images, :only => [:new, :index]
      get 'send_messages_now'
    end
  end

  match 'sms' => 'receive_text#index', :via => :post

  match ':id' => 'quotes#show'

end

app/models/quote.rb
class Quote < ActiveRecord::Base
  include UuidHelper  #Use 6-character string as ID
  before_create :set_uuid
  before_create :set_user_quote_ids 
  before_create :set_messages_scheduled_send_time
  before_save :remove_same_user_listed_more_than_once
  self.primary_key = 'id'

  belongs_to :speaker, :class_name => "User", :foreign_key => "speaker_user_id"
  belongs_to :quotifier, :class_name => "User", :foreign_key => "quotifier_user_id"
  has_many :quote_witness_users
  has_many :witnesses, :through => :quote_witness_users
  has_many :quote_images
  has_many :comments
  validates_presence_of :quotifier, :speaker, :quote_text
  validates_associated :quotifier, :speaker

  #This is the User object for the accessing user
  attr_accessor :accessing_user_obj
 
  scope :not_deleted, where("deleted = ? or deleted is null", false)
  scope :ready_to_test_for_dupes, where(" created_at > ?" , 6.hours.ago ).merge(Quote.not_deleted)
  scope :ready_to_send_message, where("messages_sent_flag = ? and messages_send_scheduled_time < ?", false, Time.now).merge(Quote.not_deleted)
  

  def is_deletable?
    if (self.created_at + 1.day > Time.now) && accessing_user_role == :quotifier then true else false end
  end

  def is_locked?
    #Whether or not the user can see the quote depends on the mode.  
    #In nostalgia or morning after mode you need to wait until the quote hatches before you can see it.
    #In quiet mode the quote is never locked and you can see it right away
    case self.mode 
    when 'nostalgia' then !(self.messages_sent_flag)
    when 'morning_after' then !(self.messages_sent_flag)
    when 'quiet' then false  
    end
  end

  #Send out email, or if we only have phone number, send text message, to quotifier, speaker, and witnesses
  def send_messages
    send_errors = []

    begin
      QuoteMailer.quotifier_email(self).deliver
    rescue Exception => e
      send_errors << e.message + "on #{self.quotifier.email}"
    end

    #If the person quotified themselves speaking, dont want to send two messages
    unless speaker.same_person_as(quotifier)
      unless speaker.email.blank?
        begin
          QuoteMailer.speaker_email(self).deliver
        rescue Exception => e
          send_errors << e.message + "on #{self.speaker.email}"
        end
      else
        send_status = QuotifyTwilio.send_twilio_message(speaker.phone, "#{quotifier.name} Quotified you!  Check it out at http://quotify.it/#{speaker_quote_id}")
        send_errors << send_status unless send_status == 'Success'
      end
    end

    quote_witness_users.each do |quote_witness|
      witness  = quote_witness.witness
      unless witness.email.blank?
        begin
          QuoteMailer.witness_email(self, witness, quote_witness).deliver
        rescue Exception => e
          send_errors << e.message + "on #{witness.email}"
        end
      else
       send_status = QuotifyTwilio.send_twilio_message(witness.phone, "#{quotifier.name} Quotified you!  Check it out at http://quotify.it/#{quote_witness.witness_quote_id}")
       send_errors << send_status unless send_status == 'Success'
      end
    end

    #Set flag that messaging has been sent.
    self.messages_sent_flag = true
    self.error_flag = ! (send_errors.empty?)
    self.error_string = send_errors.join(',')
    self.save
  end

  def deleteDupes
    Rails.logger.debug "checking for deleted quotes on  " + self.id

    quotes = Quote.where( " quote_text = ? AND id != ? AND created_at >= ? " , self.quote_text, self.id, self.created_at )
    Rails.logger.debug "deleting " + quotes.length.to_s + " objs "
    quotes.each do | quote |     
      Rails.logger.debug "deleting ID " + quote.id
      quote.deleted = 1
      quote.save
      end

  end


  #The JSON returned for a quote should include details on the speaker 
  def as_json(options={})
    super(:include => [:speaker, :witnesses], :methods => [:is_deletable?, :personalized_quote_id, :is_locked?])
  end

  def set_user_quote_ids
    self.quotifier_quote_id = Quote.get_unique_quote_id
    self.speaker_quote_id = Quote.get_unique_quote_id  
  end


  #We are going to keep unique surrogate Quote IDs for each quote for each user so when they come back we know who they are by 
  #virtue of the link.  So, need a way to generate these quickly.
  def self.get_unique_quote_id
    possible_id = Base64.encode64(UUIDTools::UUID.random_create)[0..7]
    until Quote.where("quotes.id = ? or quotes.quotifier_quote_id = ? or quotes.speaker_quote_id = ? or quote_witness_users.witness_quote_id = ?", possible_id,possible_id,possible_id,possible_id).joins(:quote_witness_users).empty?
      possible_id = Base64.encode64(UUIDTools::UUID.random_create)[0..7]
    end
    possible_id
  end

  def self.find_by_any_id(id)
    if quote = Quote.find_by_id(id) then quote.tap {|q| q.accessing_user_obj = nil} 
    elsif quote = Quote.find_by_quotifier_quote_id(id) then quote.tap{|q| q.accessing_user_obj = quote.quotifier} 
    elsif quote = Quote.find_by_speaker_quote_id(id) then  quote.tap{|q| q.accessing_user_obj =  quote.speaker} 
    elsif quote = ((qwu = QuoteWitnessUser.find_by_witness_quote_id(id)) ? qwu.quote : nil) then quote.tap{|q| q.accessing_user_obj = qwu.witness} 
    end

  end

  def personalized_quote_id
    if accessing_user_role == :quotifier then quotifier_quote_id
    elsif accessing_user_role == :speaker then speaker_quote_id
    elsif accessing_user_role == :witness
      QuoteWitnessUser.find_by_quote_id_and_user_id(self.id, accessing_user_obj).witness_quote_id
    end
  end

  def personalized_quote_id_for(user)
    if user == self.quotifier then return self.quotifier_quote_id
    elsif user == self.speaker then return self.speaker_quote_id
    else 
      quote_witness_users.each do |qwu|
        return qwu.witness_quote_id if user == qwu.witness
      end
    end
    return nil  #If we got here, there was no match
  end

  #Determine the role of the user who is accessing the quote.  This is important for things like deletability.
  def accessing_user_role
    if self.accessing_user_obj.nil? then nil
    elsif self.quotifier == accessing_user_obj then :quotifier
    elsif self.speaker == accessing_user_obj then :speaker
    else witnesses.each {|witness| if witness == accessing_user_obj then return :witness end}
    end
  end
  
  def self.all_quotes_for_users(users)
    quotes = []

    users.each { |user| 
      quotes += user.quotified_quotes.with_quote_accessor_set
      quotes += user.spoken_quotes.with_quote_accessor_set
      quotes += user.witnessed_quotes.with_quote_accessor_set
    }

    #Need better way to set default globally to not get deleted quotes, but this works for now
    quotes.delete_if{|q| q.deleted == true}

    #If the same quote is in there twice, its beacuse it was a case where the person quotified themselves as a speaker.  In that case get rid of the speaker one
    #since the quotifier one has more rights (importantly, to delete the quote)
    quotes.each do |q1| 
      if q1.accessing_user_role == :quotifier
        quotes.delete_if{|q2| q1.id == q2.id and q2.accessing_user_role == :speaker }
      end
    end

    return quotes
  end

  def mode
    #If we don't have a mode already set, assume we're using nostalgia mode as default 
    super || 'nostalgia'  
  end


  private


  def remove_same_user_listed_more_than_once
    self.witnesses.delete_if do |witness|
      self.quotifier.same_person_as(witness) || self.speaker.same_person_as(witness)
    end
  end

  def set_messages_scheduled_send_time
    #If this was already set manually somewhere else, don't override that
    return if self.messages_send_scheduled_time

    if self.mode == "quiet" 
      self.messages_send_scheduled_time = nil
    elsif self.mode == "morning_after"
      self.messages_send_scheduled_time = Time.parse((Date.today + 1.days).to_s + " 02:00PM")
    else  #Nostalgia mode, the default
      #Find all users involved in the quote and see if they have any messages that are pending being sent out
      #to avoid two nostalgia mode quotes being sent in the same day
      all_involved_users = []
      all_involved_users |= self.quotifier.find_all_similar_users 
      all_involved_users |= self.speaker.find_all_similar_users
      self.witnesses.each{|w| all_involved_users |= w.find_all_similar_users}
      all_quotes_for_involved_users = Quote.all_quotes_for_users(all_involved_users)
      max_scheduled_quote = all_quotes_for_involved_users.find_all{|q| q.messages_sent_flag == false}.max_by{|q| q.messages_send_scheduled_time}
      self.messages_send_scheduled_time = 
        if max_scheduled_quote 
          #If there are already pending quotes, make this one get sent even a little later
          max_scheduled_quote.messages_send_scheduled_time + (rand(4) + 3).days
        else
          Time.parse((Date.today + (rand(7) + 7).days).to_s + " 02:00PM") 
        end
     end

  end

end

app/controllers/admin/quotes_controller.rb
class Admin::QuotesController < ApplicationController
  layout 'admin'
  
  http_basic_authenticate_with :name => "quotify", :password => "yourmom1" 
  
  # GET /quotes
  # GET /quotes.json
  def index
    @quotes = Quote.where(" deleted = ? or deleted IS NULL ", false).order("quote_time desc")

    Mpanel.track("Admin Main Page View", { :user=> request.remote_ip })

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @quotes }
    end
  end

  # GET /quotes/new
  # GET /quotes/new.json
  def new
    @quote = Quote.new
    @quote.quotifier = User.new(name: 'Quotifier')
    @quote.speaker = User.new(name: 'Speaker')
    2.times {@quote.witnesses << User.new}

    Mpanel.track("New Quote Via Admin", { :user=> request.remote_ip })

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @quote }
    end
  end

 # GET /quotes/1/edit
  def edit
    @quote = Quote.find(params[:id])
  end


  # PUT /quotes/1
  # PUT /quotes/1.json
  def update
    @quote = Quote.find(params[:id])
    speaker = User.find_or_create(params[:quote][:speaker])
    quotifier = User.find_or_create(params[:quote][:quotifier])
    messages_send_scheduled_time = if params[:schedule_in_past_flag] then Date.yesterday else @quote.messages_send_scheduled_time end 

    Mpanel.track("Update Quote Via Admin", { :user=> request.remote_ip })

    respond_to do |format|
      if @quote.update_attributes(params[:quote].except(:speaker, :quotifier).merge({:speaker=>speaker, :quotifier=>quotifier, :messages_send_scheduled_time => messages_send_scheduled_time}))
        format.html { redirect_to @quote, notice: 'Quote was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @quote.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /quotes/1
  # DELETE /quotes/1.json
  def destroy
    @quote = Quote.find(params[:id])
    @quote.destroy

    Mpanel.track("Delete Quote Via Admin", { :user=> request.remote_ip })

    respond_to do |format|
      format.html { redirect_to quotes_url }
      format.json { head :ok }
    end
  end

  def send_messages_now

    Mpanel.track("Send Messages Via Admin", { :user=> request.remote_ip , :quote_id => params[:quote_id] })

    @quote = Quote.find(params[:quote_id])
    @quote.send_messages
    redirect_to action: "index"
  end


end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  
  respond_to :html, :json

  # @see http://www.arctickiwi.com/blog/mobile-enable-your-ruby-on-rails-site-for-small-screens
  private
  MOBILE_BROWSERS = ["android", "ipod", "opera mini", "iphone", "blackberry", "palm","hiptop","avantgo","plucker", "xiino","blazer","elaine", "windows ce; ppc;", "windows ce; smartphone;","windows ce; iemobile", "up.browser","up.link","mmp","symbian","smartphone", "midp","wap","vodafone","o2","pocket","kindle", "mobile","pda","psp","treo"]
  public

  def detect_browser
    agent = request.headers["HTTP_USER_AGENT"].downcase

    MOBILE_BROWSERS.each do |m|
      return "mobile_application" if agent.match(m)
    end
    return "application"
  end

  
  # GET /quotes/1 - 
  # GET /quotes/1.json - Used by iPhone
  def show
    @quote = Quote.find_by_any_id(params[:id])


    Mpanel.track("View Quote", { :user=> request.remote_ip , :id => params[:id] })
    Rails.logger.warn detect_browser
    respond_to do |format|
      if( detect_browser == 'mobile_application' || params[ :test_mobile ] == "1" || 1 ) 
         template = "quotes/show_mobile.html.erb" ;
      else
         template = "quotes/show.html.erb" ;
      end
      format.html { render :template => template }
      format.json { render json: @quote }
    end
  end

  #Called by a DELETE HTTP call to /quotes/:id
  def destroy
    quote = Quote.find_by_any_id(params[:id])
    if quote.is_deletable? then
      quote.deleted = true
      quote.save
      render json: { deleted: true}
    else
      render json: { deleted: false, error: "Quote is not deletable"}
    end
  end


  # GET Called from iPhone to get history for a given email address
  def history
    users = User.find_all_by_email_case_insensitive(params[:email])
    @quotes = Quote.all_quotes_for_users(users)

    Mpanel.track("View History", { :user=> request.remote_ip , :email => params[:email] })

    respond_to do |format|
      format.json { render json: {quote_history: @quotes.sort{|a,b| b.created_at <=> a.created_at} }}
    end
  end

  # POST /quotes
  # POST /quotes.json
  def create
    #TO DO: Right now, just creating a new user every time.  If we stick with this, then really dont need user model at all.  
    #If we do somehow look people up, need to make logic smarter somehow.
    speaker = User.create(params[:quote][:speaker])  
    quotifier = User.create(params[:quote][:quotifier]) 

    #Load in all the witnesses.  Since the web form is going to have blank entries for these by default, we want to exclude those entries,
    #so we do so here by taking out any entries where the name is blank.
    witnesses = params[:quote][:witnesses].map {|witness| User.create(witness) unless witness[:name].blank?} if params[:quote][:witnesses] 
    witnesses = witnesses.find_all{|w| not w.nil?}

    quote_time = params[:quote][:time] || Time.now

    #Set the scheduled time to a fixed date in the past if this admin parameter is set
    messages_send_scheduled_time = Date.yesterday if params[:schedule_in_past_flag] 

    Mpanel.track("Create Quote", { :user=> request.remote_ip , :speaker => params[:quote][:speaker], :quotifier => params[:quote][:quotifier] })

    messages_sent_flag = params[:quote][:messages_sent_flag] || false

    @quote = Quote.new(:quote_text => params[:quote][:quote_text], 
                       :quote_time => quote_time, 
                       :speaker => speaker, 
                       :quotifier => quotifier, 
                       :witnesses => (witnesses || []),
                       :location => params[:quote][:location], 
                       :coordinate=>params[:quote][:coordinate],
                       :messages_send_scheduled_time => messages_send_scheduled_time , 
                       :messages_sent_flag => messages_sent_flag,
                       :mode => params[:quote][:mode])

    flash[:notice] = 'Quote was successfully created' if @quote.save

    respond_with (@quote)
  end

end

app/helpers/admin/quotes_helper.rb
module Admin::QuotesHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/views/quotes/index.html.erb
<h1>Listing quotes</h1>

<table style="border='1px'">
  <tr>
    <th>ID</th>
    <th>Quote text</th>
    <th>Quote time</th>
    <th>Images</th>
    <th>Speaker</th>
    <th>Quotifier</th>
    <th>Witnesses</th>
    <th>Location</th>
    <th>Coordinates</th>
    <th>Email Scheduled Time</th>
    <th>Email Sent?</th>
    <th>Send Mail Now<th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @quotes.each do |quote| %>
  <tr>
    <td><%= quote.id %></td>
    <td><%= quote.quote_text %></td>
    <td><%= quote.quote_time %></td>
    <td><%= link_to quote.quote_images.count, quote_quote_images_path(quote) %></td>
    <td><%= "#{quote.speaker.name} (#{quote.speaker.email},#{quote.speaker.phone})" %></td>
    <td><%= "#{quote.quotifier.name} (#{quote.quotifier.email},#{quote.quotifier.phone})" %></td>
    <td><%= quote.witnesses.inject("") {|memo, cur| "#{memo}; #{cur[:name]} (#{cur[:email]},#{cur[:phone]})" } [2..5000] %>
    <td><%= quote.location %></td>
    <td><%= quote.coordinate %></td>
    <td><%= quote.email_send_scheduled_time %></td>
    <td><%= quote.email_sent_flag %> </td>
    <td><%= link_to 'Send Email Now', quote_send_email_now_path(quote) %></td>
    <td><%= link_to 'Show', quote %></td>
    <td><%= link_to 'Edit', edit_quote_path(quote) %></td>
    <td><%= link_to 'Destroy', quote, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Quote', new_quote_path %>

app/views/quotes/show.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= @quote.speaker.name %>'s quote | Quotify.it </title>
    <link media="screen" type="text/css" href="../assets/Styles/960.css" rel="stylesheet" />
    <link media="screen" type="text/css" href="../assets/Styles/reset.css" rel="stylesheet" />
    <link media="screen" type="text/css" href="../assets/Styles/text.css" rel="stylesheet" />
    <link media="screen" type="text/css" href="../assets/Styles/quote.css" rel="stylesheet" />
  </head>
  <body>
  
  <div id="top" class='major'>
    <div id="logo">
      <a href="../">
        <img src="../assets/Images/quote/qit.png" />
      </a>
    </div>
    <div id="quote">

      <div id="inner">
        <p id="text">
          <%= @quote.quote_text %>
        </p>


    </div>

    <div id="thumbnail">
      <% if @quote.quote_images.blank? %> 
        <img src="../assets/Images/quote/avatar.jpg" />
      <% else %>
        <%= image_tag "/quote_images/#{@quote.quote_images.first.file_name}" %>
      <% end %>
    </div>
    <div id="deets">
      <span id="speaker">
        <%= @quote.speaker.name %>
      </span>
      with 
      <span class="witness quotifier">
        <%= @quote.quotifier.name %>
      </span>
      <% @quote.witnesses.each do |witness| %> 
         ,<span class="witness">
            <%= "#{witness[:name]}" %>
         </span>
      <% end %>
      at <span id="time"><%= distance_of_time_in_words_to_now(@quote.quote_time) %></span>
    </div>
  </div>


  </div>
  <div id="comments" class='major'>

    <div id="buttons">
      <a class='download' href="download.html">
        <img src="../assets/Images/quote/download.png" />
      </a>
    </div>

            <div id="disqus_thread"></div>
        <script type="text/javascript">
            /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
            var disqus_shortname = 'quotify'; // required: replace example with your forum shortname

            /* * * DON'T EDIT BELOW THIS LINE * * */
            (function() {
                var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
                dsq.src = 'http://' + disqus_shortname + '.disqus.com/embed.js';
                (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
            })();
        </script>
        <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
        <a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>


  </div>

  
  <script type='text/javascript' src='http://ajax.googleapis.com/ajax/libs/jquery/1.4.3/jquery.min.js?ver=1.4.3'></script>  <!- Start Google Analytics -> 
  <script type='text/javascript' src='../assets/Scripts/jquery.simplemodal.js'></script>
  <script type='text/javascript' src='../assets/Scripts/index.js'></script>
  <script type="text/javascript">
  
    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', 'UA-22784176-1']);
    _gaq.push(['_trackPageview']);
  
    (function() {
      var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
      ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
      var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
    })();
  
  </script>
  <!- End Google Analytics -> 
  

  <!-- start Mixpanel --><script type="text/javascript">(function(c,a){window.mixpanel=a;var b,d,h,e;b=c.createElement("script");b.type="text/javascript";b.async=!0;b.src=("https:"===c.location.protocol?"https:":"http:")+'//api.mixpanel.com/site_media/js/api/mixpanel.2.js';d=c.getElementsByTagName("script")[0];d.parentNode.insertBefore(b,d);a._i=[];a.init=function(b,c,f){function d(a,b){var c=b.split(".");2==c.length&&(a=a[c[0]],b=c[1]);a[b]=function(){a.push([b].concat(Array.prototype.slice.call(arguments,0)))}}var g=a;"undefined"!==
typeof f?g=a[f]=[]:f="mixpanel";g.people=g.people||[];h="disable track track_pageview track_links track_forms register register_once unregister identify name_tag set_config people.set people.increment".split(" ");for(e=0;e<h.length;e++)d(g,h[e]);a._i.push([b,c,f])};a.__SV=1.1})(document,window.mixpanel||[]);
mixpanel.init("10db5716f34ad4fa4aead789301c232b");</script><!-- end Mixpanel -->
  
<script type="text/javascript">
    mixpanel.track("Quotes Page Pageview")
</script>

  </body>

</html>

app/views/quotes/show_mobile.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= @quote.speaker.name %>'s quote | Quotify.it </title>
    <link media="screen" type="text/css" href="../assets/Styles/960.css" rel="stylesheet" />
    <link media="screen" type="text/css" href="../assets/Styles/reset.css" rel="stylesheet" />
    <link media="screen" type="text/css" href="../assets/Styles/text.css" rel="stylesheet" />
    <link media="screen" type="text/css" href="../assets/Styles/quote_mobile.css" rel="stylesheet" />
  </head>
  <body>
  
  <div id="container">
  <div id="top" class='major'>
    <div id="logo">
      <a href="/">
        <img src="../assets/Images/quote/qit.png" />
      </a>
    </div>
    <div id="quote">
      <div id="inner">
        <p id="text">
          <%= @quote.quote_text %>
        </p>
    </div>
    <img id="left_bub" src="../assets/Images/quote/quote/bubbles_left.png" />
    <img id="right_bub" src="../assets/Images/quote/quote/bubbles_right.png" />
    <div id="thumbnail">
      <% if @quote.quote_images.blank? %> 
        <img src="../assets/Images/quote/avatar.jpg" />
      <% else %>
        <%= image_tag "/quote_images/#{@quote.quote_images.first.file_name}" %>
      <% end %>
    </div>
    <div id="deets">
      <span id="speaker">
        <%= @quote.speaker.name %>
      </span>
      <% unless @quote.speaker.same_person_as(@quote.quotifier) %>
        with <span class="witness quotifier"><%= @quote.quotifier.name %></span>
      <% end %>
      <% @quote.witnesses.each do |witness| %> & <span class="witness"><%= "#{witness[:name]}" %></span> <% end %>
     <span id="time">| <%= distance_of_time_in_words_to_now(@quote.quote_time) %> ago</span>
    </div>
  </div>


  </div>



  <div id="comments" class='major'>

  <form id="submitcomment" action="../../../../quotes/<%=@quote.id%>/comments" method="post" >
    <input type="hidden" name="comment[commenter_name]" value="<%=@quote.accessing_user_obj ?  @quote.accessing_user_obj.name : 'Anonymous' %>" />
    <input type="hidden" name="comment[user_id]" value="<%=@quote.accessing_user_obj ?  @quote.accessing_user_obj.id : nil %>" />
    <input type="text" name="comment[comment_text]" placeholder="Type your comment here.." />
    <input type="submit" name="submit" value="comment" />
  </form>

  <ul>
    <% if @quote.comments.length == 0 %>
    <li class="nocomments">
        No comments yet.  Add yours above!
    </li>
    <% end %>
    <% @quote.comments.each_with_index do | comment,i | %>
    <li class="<%= i % 2 == 1 ? 'even' : 'odd' %>">
        <span class="name">
          <%= comment.commenter_name %>
        </span>
        <span class="date">
          <%= distance_of_time_in_words_to_now(comment.created_at) %> ago
        </span>
        <p class="quote">
          <%= comment.comment_text %>
        </p>
    </li>
    <% end %>
  </ul>

  </div>

  
  <script type="text/javascript">
  
    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', 'UA-22784176-1']);
    _gaq.push(['_trackPageview']);
  
    (function() {
      var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
      ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
      var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
    })();
  
  </script>
  <!- End Google Analytics -> 
  

  <!-- start Mixpanel --><script type="text/javascript">(function(c,a){window.mixpanel=a;var b,d,h,e;b=c.createElement("script");b.type="text/javascript";b.async=!0;b.src=("https:"===c.location.protocol?"https:":"http:")+'//api.mixpanel.com/site_media/js/api/mixpanel.2.js';d=c.getElementsByTagName("script")[0];d.parentNode.insertBefore(b,d);a._i=[];a.init=function(b,c,f){function d(a,b){var c=b.split(".");2==c.length&&(a=a[c[0]],b=c[1]);a[b]=function(){a.push([b].concat(Array.prototype.slice.call(arguments,0)))}}var g=a;"undefined"!==
typeof f?g=a[f]=[]:f="mixpanel";g.people=g.people||[];h="disable track track_pageview track_links track_forms register register_once unregister identify name_tag set_config people.set people.increment".split(" ");for(e=0;e<h.length;e++)d(g,h[e]);a._i.push([b,c,f])};a.__SV=1.1})(document,window.mixpanel||[]);
mixpanel.init("10db5716f34ad4fa4aead789301c232b");</script><!-- end Mixpanel -->
  
<script type="text/javascript">
    mixpanel.track("Mobile Quotes Page Pageview");
</script>
</div>
  </body>

</html>