config/routes.rb
Quotify::Application.routes.draw do
  resources :users

  resources :quotes, :only => [:show, :create, :destroy] do 
    get 'history', :on => :collection
    resources :quote_images, :only => [:show, :create]
    resources :comments, :only => [:create, :new]
  end

  namespace :admin do
    resources :quotes, :only => [:new, :index, :edit, :update] do 
      resources :quote_images, :only => [:new, :index]
      get 'send_messages_now'
    end
  end

  match 'sms' => 'receive_text#index', :via => :post

  match ':id' => 'quotes#show'

end

app/models/quote_image.rb
class QuoteImage < ActiveRecord::Base
  include UuidHelper  #Use 6-character string as ID
  before_create :set_uuid
  self.primary_key = 'id'

  belongs_to :quote
  attr_accessor :image_data   #Temporary store for image binary data until it is written to disk
  after_create :save_image_data
  validates_presence_of :name, :image_data
  
  def save_image_data
    directory = "public/quote_images"
    file_name =  self.id.to_s + "_" + SecureRandom.hex(4).to_s + "." + self.image_data.original_filename.split(".").last 
    path = File.join(directory, file_name)
    File.open(path, "wb") { |f| f.write(self.image_data.read) }
    self.update_attribute(:file_name, file_name)
  end
  
end

app/controllers/admin/quote_images_controller.rb
class Admin::QuoteImagesController < ApplicationController
  http_basic_authenticate_with :name => "quotify", :password => "yourmom1" 
  before_filter { |controller| @quote = Quote.find(params[:quote_id]) }

  # GET /quote_images
  # GET /quote_images.json
  def index
    @quote_images = @quote.quote_images.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @quote_images }
    end
  end

  # GET /quote_images/new
  def new
    @quote_image = QuoteImage.new

    respond_to do |format|
      format.html # new.html.erb
    end
  end


end

app/controllers/quote_images_controller.rb
class QuoteImagesController < ApplicationController
  #All methods need to get a reference to the parent quote
  before_filter { |controller| @quote = Quote.find(params[:quote_id]) }
  protect_from_forgery :except => :create  # No checking for token from app image creation request

 
  # GET /quote_images/1
  # GET /quote_images/1.json
  def show
    @quote_image = @quote.quote_images.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @quote_image }
    end
  end

  # POST /quote_images
  # POST /quote_images.json
  def create
    @quote_image = QuoteImage.new(params[:quote_image].merge({:quote_id => @quote.id}))  #Add in the parent quote id from the URL

    respond_to do |format|
      if @quote_image.save
        format.html { redirect_to quote_quote_image_path(@quote, @quote_image), notice: 'Quote image was successfully created.' }
        format.json { render json: @quote_image, status: :created }
      else
        format.html { render action: "new" }
        format.json { render json: @quote_image.errors, status: :unprocessable_entity }
      end
    end
  end



end

app/helpers/admin/quote_images_helper.rb
module Admin::QuoteImagesHelper
end

app/helpers/quote_images_helper.rb
module QuoteImagesHelper
end

app/views/admin/quote_images/_form.html.erb
<%= form_for(@quote_image, :url=> quote_quote_images_path(@quote)) do |f| %>
  <% if @quote_image.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@quote_image.errors.count, "error") %> prohibited this quote_image from being saved:</h2>

      <ul>
      <% @quote_image.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
  	<div class="field">
      <%= f.label :name %><%= f.text_field :name %><br />
      <%= f.label :file %><%= f.file_field :image_data %>
    </div>
      <%= f.submit %>
  </div>
<% end %>

app/views/admin/quote_images/index.html.erb
<h1>Listing Images for Quote <%=@quote.id%></h1>

<table>
  <tr>
  	<th>Name</th>
    <th></th>
    
  </tr>

<% @quote_images.each do |quote_image| %>
  <tr>
  	<td><%= quote_image.name %></td>
    <td><%= link_to 'Show', quote_quote_image_path(@quote, quote_image) %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Quote image', new_admin_quote_quote_image_path(@quote)  %>

app/views/admin/quote_images/new.html.erb
<h1>New Image For Quote <%= @quote.id %></h1>

<%= render 'form' %>

<%= link_to 'Back', quote_quote_images_path(@quote) %>